@startuml "Compra de Ingressos"
left to right direction

:Cliente: as cliente


rectangle "Sistema de Ingressos"{
    (Realizar Cadastro) as realizar_cadastro
    (Realizar Login) as realizar_login
    (Buscar Filmes) as buscar_filmes
    (Comprar Ingresso) as comprar_ingresso
    (Comprar no PIX) as comprar_pix
    (Comprar no Crédito) as comprar_credito
    (Listar Ingressos) as listar_ingressos
}

cliente --> realizar_cadastro
cliente --> buscar_filmes
cliente --> comprar_ingresso
cliente --> listar_ingressos

comprar_ingresso ..> realizar_login: <<include>
comprar_pix -right-|> comprar_ingresso
comprar_credito -up-|> comprar_ingresso


@enduml