@startuml
left to right direction

class Ingresso{
    id
    valor
    evento
    cliente
    lote
    data_emissao
    data_evento
    setor
    situacao
}

class TelaIngresso{
    campo_id
    campo_valor
    campo_evento
    campo_cliente
    campo_lote
    campo_data_emissao
    campo_data_evento
    campo_setor
    campo_situacao
    botao_enviar
    enviar()
}

class ControleIngresso{
    realizar_reembolso()
    realizar_compra()
    realizar_validacao()
}

class Evento{
    id
    nome
    local
    horario
    data
    qnt_maxima
    tipo
    lotes
    ingressos_vendidos
    situacao
    motivo_cancelamento
    motivo_adiamento
    organizador
    
}

class TelaEvento{
    campo_nome
    campo_local
    campo_horario
    campo_data
    campo_qnt_maxima
    campo_tipo
    campo_lotes
    campo_situacao
    campo_motivo_cancelamento
    campo_motivo_adiamento
    campo_organizador
    botao_enviar
    enviar()
}

class ControleEvento{
    listar_clientes()
    cadastrar_evento()
    atualizar_evento()
    remover_evento()
    listar_eventos()
}


class Cliente{
    id
    nome
    telefone
    email
    cpf
    ingressos
 
}

class TelaCliente{
    campo_nome
    campo_telefone
    campo_email
    campo_cpf
    campo_ingressos
    botao_enviar
    enviar()
}

class ControleCliente{
    cadastrar_cliente()
    atualizar_cliente()
    remover_cliente()
    listar_clientes()
}

class Organizador{
    id
    nome
    email
    telefone
    eventos
    cpf_cnpj
}

class TelaOrganizador{
    campo_nome
    campo_email
    campo_telefone
    campo_eventos
    campo_cpf_cnpj
    botao_enviar
    enviar()
}

class ControleOrganizador{
    cadastrar_organizador()
    atualizar_organizador()
    remove_organizador()
    listar_organizadores()
}

class Lote{
    id
    quantidade_ingressos
    data_inicio
    data_fim
    valor
}

class TelaLote{
    campo_quantidade_ingressos
    campo_data_inicio
    campo_data_fim
    campo_valor
    botao_enviar
    enviar()
}

class ControleLote{
    cadastrar_lote()
    listar_lotes()
    atualizar_lotes()
    remover_lotes()
}

class Local{
    id
    nome
    endereco
    capacidade_max
    tipo
    agenda_eventos
}

class TelaLocal{
    campo_nome
    campo_endereco
    campo_capacidade_max
    campo_tipo
    campo_agenda_eventos
    botao_enviar
    enviar()
}

class ControleLocal{
    cadastrar_local()
    atualizar_local()
    remover_local()
    listar_locais()
}

Ingresso "0..*"--"1..*" Cliente: < possui
Ingresso "1..*"--"1..*" Lote: < possui
Ingresso "*"--"1..*" Evento: < possui

Evento "1"--"1" Local: possui >
Evento "1"--"1..*" Lote: possui >
Evento "1..*"--"1..*" Organizador: possui >

TelaIngresso "1"--"1" ControleIngresso: solicita > 
ControleIngresso "1"--"0..*" Ingresso: controla >

TelaCliente -- ControleCliente: solicita >
ControleCliente -- Cliente: controla >

TelaLote -- ControleLote: solicita >
ControleLote -- Lote: controla >

TelaEvento -- ControleEvento: solicita >
ControleEvento -- Evento: controla >

TelaLocal -up- ControleLocal: solicita >
ControleLocal -up- Local: controla >

TelaOrganizador -- ControleOrganizador: solicita >
ControleOrganizador -- Organizador: controla >

ControleEvento -- ControleIngresso: solicita >
ControleIngresso -- ControleCliente: solicita >

ControleEvento -- ControleLocal: solicita >
ControleEvento -- ControleLote: solicita >

@enduml