@startuml


class "Funcionario"{
    -id: int
    -nome: String
    -cargo: String
    -login: String
    -senha: Password
    +login(login: String, password: Passord): boolean
    +logout(): boolean
}


class "Pedido"{
    -id:int
    -mesa: int
    -itens: List<Item>
    -status: String
    -funcionario: Funcionario
    +adicionar_item(item: Item): boolean
    +remover_item(item: Item): boolean
    +realizar_pedido(itens: List<Item>): boolean
    +aceitar_pedido(): int
    +visualizar_pedidos(): List<Pedido>
    +cancelar_pedido(): boolean
    +atualizar_status(novo: String): boolean
    +listar_itens(): List<Item>
    +confirmar_pagamento(): boolean
}

class Item{
    -id: int
    -nome: String
    -descricao: String
    -valor_unitario: float
    -valor_total: float
    -quantidade: int
    -disponibilidade: boolean
    +atualizar_disponibilidade(): boolean
    +calcular_total(): boolean
}

class "Pagamento"{
    -pedidos: List<Pedido>
    -valor_total: float
    -status: String
    -metodo: String
    -mesa: int
    -desconto: float
    -data: Date
    -hora: Time
    +encerrar_mesa(id_mesa: int): boolean
    +calcular_total(): float
    +gerar_recibo(): void
    +atulizar_status(novo: String): boolean
}

class "Caixa"{
    -pedidos: List<Pedido>
    -data_incio: Date
    -data_fim: Date
    -entrada: float
    -saida: float
    -saldo: float
    -funcionario: Funcionario
    +abrir_caixa(): boolean
    +fechar_caixa(): boolean
    +gerar_relatorio_dia(): void
    +gerar_relatorio_mes(): void
    +gerar_relatorio_ano(): void
}

class Notificacao{
    +notificar(cargo: String, msg: String): boolean
    +notificar_por_pedido(id_pedido: int, msg: String): boolean
    +notificar_por_garcom(id_garcom: int, msg: String): boolean
}

Funcionario "1"--"1" Pedido: registra >
Pedido o-left- Item
Caixa "1..*"--"*" Pedido: lista >
Pedido "1"-right-"*" Notificacao: gera >
Pagamento "1"--"1" Pedido: possui >

@enduml