@startuml "Notas Alunos"
hide footbox

actor Professor
participant FronteiraNotas
participant ControleNotas
participant Notas
participant Disciplina
participant ControleDisciplina
participant Aluno
participant ControleAluno

Professor -> FronteiraNotas: 1:solicitaMedia(matricula: String, id_disciplina: String): boolean
activate FronteiraNotas

FronteiraNotas -> ControleNotas: 1.1:solicitaMedia(matricula, id_disciplina)
activate ControleNotas

ControleNotas -> ControleDisciplina: 1.1.1:getDisciplina(id_disciplina): Disciplina
activate ControleDisciplina

create Disciplina
ControleDisciplina -> Disciplina: <<create>>
activate Disciplina

ControleNotas -> ControleAluno: 1.1.2:getAluno(matricula): Aluno
activate ControleAluno

create Aluno
ControleAluno -> Aluno: <<create>>
activate Aluno

ControleDisciplina --> ControleNotas
deactivate ControleDisciplina

ControleAluno --> ControleNotas
deactivate ControleAluno

create Notas
ControleNotas -> Notas: <<create>>
activate Notas

ControleNotas -> ControleNotas: 1.1.3:calcularMedia(notas): float
activate ControleNotas

ControleNotas --> FronteiraNotas
deactivate Disciplina
deactivate Aluno
deactivate Notas
deactivate ControleNotas
deactivate ControleNotas

FronteiraNotas --> Professor
deactivate FronteiraNotas


@enduml